### ISSUE TITLE
Videoplayer no longer working after updating to 2.0

### ISSUE THREAD

**Issue by PaulVrugt** [inthehand/InTheHand.Forms#60]
We're in the process of updating our nuget packages of our xamarin.forms apps. This package is one of the packages being updated. However, after updating to 2.0.2019.716 or higher, our video player doesn't work anymore. Neither in Android nor iOS.

We use an empty forms page with a stacklayout on it, containing a MediaElement control. We use a https url as source, and have custom headers because the url points to an API for which we need to authenticate. the code looks like this:

            var contentStack = new StackLayout() { Orientation = StackOrientation.Vertical, Spacing = 0 };
            Content = contentStack;

            _mediaElement = new InTheHand.Forms.MediaElement();
            _mediaElement.HorizontalOptions = LayoutOptions.Fill;
            _mediaElement.VerticalOptions = LayoutOptions.Center;
            _mediaElement.BackgroundColor = Color.Black;
            _mediaElement.HeightRequest = 400;

            _mediaElement.AutoPlay = true;

            _mediaElement.HttpHeaders.Add("Authorization", $"bearer {<A token>}");
            _mediaElement.Source = new Uri("<the url>");

            _mediaElement.ShowsPlaybackControls = true;
            contentStack.Children.Add(_mediaElement);

This code worked fine on 1.0.2019.118. After upgrading it doesn't work anymore. Could this have something to do with custom headers?

Is there a problem is (for now) not upgrading? The 2.0 version claims to have XF4.0 support. We are using XF4.0, and the 1.0.2019.118 seems to also work with XF4.0

What can we do to fix this issue?

**Comment by peterfoot** [comment]
That's odd. You can definitely use the v1.0 version with newer versions of XF but 2.0 has some optimisations (e.g. fast renderers). Do you definitely have the InTheHandForms.Init call in your platform project startup?

**Comment by PaulVrugt** [comment]
wow that was fast. Yes I'm calling the Init. I'm sot sure what I can do to find the issue. There is no logging of anything when the player opens, and it used to work fine.

**Comment by PaulVrugt** [comment]
As some extra info:
we use the component as follows:

- A webview opens a document, in which media can be embedded
- When the document contains a video, we show an image of a play button
- When the play button is clicked, we execute some code that does a pushmodalasync of the page shown in the example

We currently downgraded back to the 1.x version until the issue is found and we can upgrade again

**Comment by peterfoot** [comment]
Hi, it looks like in the transition part of the HttpHeaders implementation in the native renderer was lost and so these are not being passed. I'm working on a fix.

**Comment by PaulVrugt** [comment]
Great!

**Comment by peterfoot** [comment]
This should now be fixed in the latest NuGet 2.0.2019.815

**Comment by PaulVrugt** [comment]
Nice! I'll check it out Monday!

**Comment by PaulVrugt** [comment]
hurray, it works again! thanks

**Comment by PaulVrugt** [comment]
@peterfoot 
Hmm we ran into a little snag. I didn't test the new package myself, but a collegue told me it works now. This is true for android, but for iOS it seems even more broken than it was. Now iOS still doesn't play the video. I've debugged, and it seems in iOS the http source is not even requested (no call is ever done).

Furthermore, when closing the page that is displaying the mediaelement control, an exception occurs:

SIGABRT: Cannot access a disposed object. Object name: 'MediaElementRenderer'.
NSObject.get_SuperHandle ()
UIViewController.get_View ()
IVisualElementRenderer.get_NativeView ()
VisualElementPackager.OnChildRemoved (Xamarin.Forms.VisualElement view)
VisualElementPackager.SetElement (Xamarin.Forms.VisualElement oldElement, Xamarin.Forms.VisualElement newElement)
VisualElementPackager.Dispose (System.Boolean disposing)
VisualElementRenderer`1[TElement].Dispose (System.Boolean disposing)
NSObject.Dispose ()
DisposeHelpers.DisposeModalAndChildRenderers (Xamarin.Forms.Element view)
INavigation.PopModalAsync (System.Boolean animated)

For now, we have downgraded to 1.0 again

**Comment by peterfoot** [comment]
Sorry, I think I only read Android as the affected platform (because someone else reported just that separately). I will get back on it and attack the iOS renderer next week

**Comment by peterfoot** [comment]
Hi, just an update - I've fixed the original bug where the video is not showing however I haven't done a release yet as I've found another bug with layout when the device is rotated, hope to have a fix shortly, if not a simple fix I'll release a preview nuget package to at least confirm the original issue is resolved.

**Comment by peterfoot** [comment]
Please check out the latest release on NuGet

**Comment by PaulVrugt** [comment]
@peterfoot sorry for the late reply, we were a bit busy and also had trouble updating to XF4.2

I've tried the new update, and the video now also plays on iOS. However, when closing the popup containing the mediaplayer, the app crashes:

<details>
  <summary>complete error (click to expand)</summary>

**System.ArgumentNullException:** 'Value cannot be null.
Parameter name: element'

2019-09-13 10:48:58.804 
Unhandled Exception:
System.ArgumentNullException: Value cannot be null.
Parameter name: element
  at InTheHand.Forms.Platform.iOS.MediaElementRenderer.Xamarin.Forms.Platform.iOS.IVisualElementRenderer.SetElement (Xamarin.Forms.VisualElement element) [0x00003] in C:\Users\peter\Source\Repos\inthehand\InTheHand.Forms\InTheHand.Forms\InTheHand.Forms.Platform.iOS\MediaElementRenderer.cs:454 
  at InTheHand.Forms.Platform.iOS.MediaElementRenderer.Dispose (System.Boolean disposing) [0x000c6] in C:\Users\peter\Source\Repos\inthehand\InTheHand.Forms\InTheHand.Forms\InTheHand.Forms.Platform.iOS\MediaElementRenderer.cs:219 
  at Foundation.NSObject.Dispose () [0x00000] in /Library/Frameworks/Xamarin.iOS.framework/Versions/12.14.0.114/src/Xamarin.iOS/Foundation/NSObject2.cs:147 
  at Xamarin.Forms.Platform.iOS.VisualElementPackager.Dispose (System.Boolean disposing) [0x0003f] in D:\a\1\s\Xamarin.Forms.Platform.iOS\VisualElementPackager.cs:69 
  at Xamarin.Forms.Platfo
rm.iOS.VisualElementPackager.Dispose () [0x00000] in D:\a\1\s\Xamarin.Forms.Platform.iOS\VisualElementPackager.cs:37 
  at Xamarin.Forms.Platform.iOS.VisualElementRenderer`1[TElement].Dispose (System.Boolean disposing) [0x00058] in <307bb0d1b0ac4e7c9dc8252978e366cc>:0 
  at Foundation.NSObject.Dispose () [0x00000] in /Library/Frameworks/Xamarin.iOS.framework/Versions/12.14.0.114/src/Xamarin.iOS/Foundation/NSObject2.cs:147 
  at Xamarin.Forms.Platform.iOS.DisposeHelpers.DisposeModalAndChildRenderers (Xamarin.Forms.Element view) [0x00041] in D:\a\1\s\Xamarin.Forms.Platform.iOS\DisposeHelpers.cs:23 
  at Xamarin.Forms.Platform.iOS.Platform.Xamarin.Forms.INavigation.PopModalAsync (System.Boolean animated) [0x00143] in D:\a\1\s\Xamarin.Forms.Platform.iOS\Platform.cs:119 
  at Xamarin.Forms.Application+NavigationImpl.OnPopModal (System.Boolean animated) [0x0005d] in D:\a\1\s\Xamarin.Forms.Core\Application.cs:380 
  at Infoland.Xamarin.Shared.General+<>c__DisplayClass75_0.<GoBackAsync>b__0 () [0x00257] in C:\Users\p
.vrugt\Source\Repos\Apps\Infoland.Xamarin.Shared\Infoland.Xamarin.Shared\General\General.cs:1228 
  at Infoland.Xamarin.Shared.General.GoBackAsync () [0x00057] in C:\Users\p.vrugt\Source\Repos\Apps\Infoland.Xamarin.Shared\Infoland.Xamarin.Shared\General\General.cs:1250 
  at Infoland.Xamarin.Shared.Controls.AudioVideo+<>c.<.ctor>b__2_0 () [0x00019] in C:\Users\p.vrugt\Source\Repos\Apps\Infoland.Xamarin.Shared\Infoland.Xamarin.Shared\Controls\DocumentViewer\AudioVideo.cs:27 
  at System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__7_0 (System.Object state) [0x00000] in /Library/Frameworks/Xamarin.iOS.framework/Versions/12.14.0.114/src/Xamarin.iOS/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/AsyncMethodBuilder.cs:1021 
  at Foundation.NSAsyncSynchronizationContextDispatcher.Apply () [0x00000] in /Library/Frameworks/Xamarin.iOS.framework/Versions/12.14.0.114/src/Xamarin.iOS/Foundation/NSAction.cs:178 
  at (wrapper managed-to-native) UIKit.UIApplication.UIApplicationMa
in(int,string[],intptr,intptr)
  at UIKit.UIApplication.Main (System.String[] args, System.IntPtr principal, System.IntPtr delegate) [0x00005] in /Library/Frameworks/Xamarin.iOS.framework/Versions/12.14.0.114/src/Xamarin.iOS/UIKit/UIApplication.cs:86 
  at UIKit.UIApplication.Main (System.String[] args, System.String principalClassName, System.String delegateClassName) [0x0000e] in /Library/Frameworks/Xamarin.iOS.framework/Versions/12.14.0.114/src/Xamarin.iOS/UIKit/UIApplication.cs:65 
2019-09-13 10:48:58.812 Unhandled managed exception: Value cannot be null.
Parameter name: element (System.ArgumentNullException)
  at InTheHand.Forms.Platform.iOS.MediaElementRenderer.Xamarin.Forms.Platform.iOS.IVisualElementRenderer.SetElement (Xamarin.Forms.VisualElement element) [0x00003] in C:\Users\peter\Source\Repos\inthehand\InTheHand.Forms\InTheHand.Forms\InTheHand.Forms.Platform.iOS\MediaElementRenderer.cs:454 
  at InTheHand.Forms.Platform.iOS.MediaElementRenderer.Dispose (System.Boolean disposing) [0x000c6] in C:\Users\peter\Source\Repos\inthehand\InTheHand.Forms\InTheHand.Forms\InTheHand.Forms.Platform.iOS\MediaElementRenderer.cs:219 
  at Foundation.NSObject.Dispose () [0x00000] in /Library/Frameworks/Xamarin.iOS.framework/Versions/12.14.0.114/src/Xamarin.iOS/Foundation/NSObject2.cs:147 
  at Xamarin.Forms.Platform.iOS.VisualElementPackager.Dispose (System.Boolean disposing) [0x0003f] in D:\a\1\s\Xamarin.Forms.Platform.iOS\VisualElementPackager.cs:69 
  at Xamarin.Form
s.Platform.iOS.VisualElementPackager.Dispose () [0x00000] in D:\a\1\s\Xamarin.Forms.Platform.iOS\VisualElementPackager.cs:37 
  at Xamarin.Forms.Platform.iOS.VisualElementRenderer`1[TElement].Dispose (System.Boolean disposing) [0x00058] in <307bb0d1b0ac4e7c9dc8252978e366cc>:0 
  at Foundation.NSObject.Dispose () [0x00000] in /Library/Frameworks/Xamarin.iOS.framework/Versions/12.14.0.114/src/Xamarin.iOS/Foundation/NSObject2.cs:147 
  at Xamarin.Forms.Platform.iOS.DisposeHelpers.DisposeModalAndChildRenderers (Xamarin.Forms.Element view) [0x00041] in D:\a\1\s\Xamarin.Forms.Platform.iOS\DisposeHelpers.cs:23 
  at Xamarin.Forms.Platform.iOS.Platform.Xamarin.Forms.INavigation.PopModalAsync (System.Boolean animated) [0x00143] in D:\a\1\s\Xamarin.Forms.Platform.iOS\Platform.cs:119 
  at Xamarin.Forms.Application+NavigationImpl.OnPopModal (System.Boolean animated) [0x0005d] in D:\a\1\s\Xamarin.Forms.Core\Application.cs:380 
  at Infoland.Xamarin.Shared.General+<>c__DisplayClass75_0.<GoBackAsync>b__0 () [0x00257] in C:
\Users\p.vrugt\Source\Repos\Apps\Infoland.Xamarin.Shared\Infoland.Xamarin.Shared\General\General.cs:1228 
  at Infoland.Xamarin.Shared.General.GoBackAsync () [0x00057] in C:\Users\p.vrugt\Source\Repos\Apps\Infoland.Xamarin.Shared\Infoland.Xamarin.Shared\General\General.cs:1250 
  at Infoland.Xamarin.Shared.Controls.AudioVideo+<>c.<.ctor>b__2_0 () [0x00019] in C:\Users\p.vrugt\Source\Repos\Apps\Infoland.Xamarin.Shared\Infoland.Xamarin.Shared\Controls\DocumentViewer\AudioVideo.cs:27 
  at System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__7_0 (System.Object state) [0x00000] in /Library/Frameworks/Xamarin.iOS.framework/Versions/12.14.0.114/src/Xamarin.iOS/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/AsyncMethodBuilder.cs:1021 
  at Foundation.NSAsyncSynchronizationContextDispatcher.Apply () [0x00000] in /Library/Frameworks/Xamarin.iOS.framework/Versions/12.14.0.114/src/Xamarin.iOS/Foundation/NSAction.cs:178 
  at (wrapper managed-to-native) UIKit.UIApplication.UIAppli
cationMain(int,string[],intptr,intptr)
  at UIKit.UIApplication.Main (System.String[] args, System.IntPtr principal, System.IntPtr delegate) [0x00005] in /Library/Frameworks/Xamarin.iOS.framework/Versions/12.14.0.114/src/Xamarin.iOS/UIKit/UIApplication.cs:86 
  at UIKit.UIApplication.Main (System.String[] args, System.String principalClassName, System.String delegateClassName) [0x0000e] in /Library/Frameworks/Xamarin.iOS.framework/Versions/12.14.0.114/src/Xamarin.iOS/UIKit/UIApplication.cs:65 
CalabashServer | XTC_SKIP_LPSERVER_TOKEN is not in the app environment
CalabashServer | Will start LPServer with identifier: e8754b3cd4c478021b7b5f5654606d3a9bc25485

=================================================================
	Native Crash Reporting
=================================================================
Got a SIGABRT while executing native code. This us
ually indicates
a fatal error in the mono runtime or one of the native libraries 
used by your application.
=================================================================

=================================================================
	Basic Fault Adddress Reporting
=================================================================
Memory around native instruction pointer (0x18ace3104):0x18ace30f4  fd 7b 
29 80 d2 01 10 00 d4  .{...
c1 a8 c0 03 5f d6 10 
._..)......
0x18ace3104  c3 00 00 54 fd 7b bf a9 
fd 03 00 91 bc d5 ff 97  ...
T.{.........
.
0x18ace3114  bf 03 00 91 fd 7b c1 a8 c0 
03 5f d6 90 29 80 d2  ...
..{...._..
)..
0x18ace3124  01 10 00 d4 c3 
00 00 54 fd 7b bf a9 fd 03 00 91  .......T.{..
....

=================================================================
	Native stacktrace:
=================================================================
	0x102a74c48 - /var/containers/Bundle/Application/DB54657E-F34B-4F3E-A650-4C6761A228CC/xxx.iOS.app/xxx.iOS : (null)
	0x102a6a768 - /var/containers/Bundle/Application/DB54657E-F34B-4F3E-A650-4C6761A228CC/xxx.iOS.app/xxx.iOS : (null)
	0x18ad58a20 - /usr/lib/system/libsystem_platform.dylib : <redacted>
	0x18ad5e070 - /usr/lib/system/libsystem_pthread.dylib : <redacted>
	0x18ac3ad78 - /usr/lib/system/libsystem_c.dylib : abort
	0x102c204c0 - /var/containers/Bundle/Application/DB54657E-F34B-4F3E-A650-4C6761A228CC/xxx.iOS.app/xxx.iOS : xamarin_get_block_descriptor
	0x102ad518c - /var/containers/Bundle/Application/DB54657E-F34B-4F3E-A650-4C6761A228CC/xxx.iOS.app/xxx.iOS : mono_pmip
	0x102a6a190 - /var/containers/Bundle/Application/DB54657E-F34B-4F3E-A650-4C6761A228CC/xxx.iOS.app/xxx.iOS : (null)
	0x102a68c68 - /var/containers/Bundle/Application/DB54657E-F34B-4F3E-A650-4C6761A228CC/xxx.iOS.app/xxx.iOS : (null)
	0x102a5e25c - /var/containers/Bundle/Application/DB54657E-F34B-4F3E-A650-4C6761A228CC/xxx.iOS.app/xxx.iOS : (null)
	0x1009a0adc - /var/containers/Bundle/Application/DB54657E-F34B-4F3E-A650-4C6761A228CC/xxx.iOS.app/xxx.iOS : (null)
	0x1007406a4 - /var/containers/Bundle/Application/DB54657E-F34B-4F3E-A650-4C6761A228CC/xxx.iOS.app/xxx.iOS : (null)
	0x10074749c - /var/containers/Bundle/Application/DB54657E-F34B-4F3E-A650-4C6761A228CC/xxx.iOS.app/xxx.iOS : (null)
	0x10168ce44 - /var/containers/Bundle/Application/DB54657E-F34B-4F3E-A650-4C6761A228CC/xxx.iOS.app/xxx.iOS : (null)
	0x10096088c - /var/containers/Bundle/Application/DB54657E-F34B-4F3E-A650-4C6761A228CC/xxx.iOS.app/xxx.iOS : (null)
	0x102a7cabc - /var/containers/Bundle/Application/DB54657E-F34B-4F3E-A650-4C6761A228CC
/xxx.iOS.app/xxx.iOS : mono_pmip
	0x102b35494 - /var/containers/Bundle/Application/DB54657E-F34B-4F3E-A650-4C6761A228CC/xxx.iOS.app/xxx.iOS : mono_pmip
	0x102b38ee4 - /var/containers/Bundle/Application/DB54657E-F34B-4F3E-A650-4C6761A228CC/xxx.iOS.app/xxx.iOS : mono_pmip
	0x10057adac - /var/containers/Bundle/Application/DB54657E-F34B-4F3E-A650-4C6761A228CC/xxx.iOS.app/xxx.iOS : (null)
	0x10057e7a0 - /var/containers/Bundle/Application/DB54657E-F34B-4F3E-A650-4C6761A228CC/xxx.iOS.app/xxx.iOS : (null)
	0x18bbfe39c - /System/Library/Frameworks/Foundation.framework/Foundation : <redacted>
	0x18b0dc1cc - /System/Library/Frameworks/CoreFoundation.framework/CoreFoundation : <redacted>
	0x18b0dc14c - /System/Library/Frameworks/CoreFoundation.framework/CoreFoundation : <redacted>
	0x18b0dba30 - /System/Library/Frameworks/CoreFoundation.framework/CoreFoundation : <redacted>
	0x18b0d68fc - /System/Library/Frameworks/CoreFoundation.framework/CoreFoundation : <redacted>
	0x18b0d61cc - /System/Library/Frameworks/CoreFoundation.framework/CoreFoundation : CFRunLoopRunSpecific
	0x18d34d584 - /System/Library/PrivateFrameworks/GraphicsServices.framework/GraphicsServices : GSEventRunModal
The app has been terminated.
Failed to Stop app:  An error occurred on client IDB162095 while executing a reply for topic xvs/idb/16.2.0.95/stop-app
	0x1b81d1054 - /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore : UIApplicationMain
	0x1016f4e20 - /var/containers/Bundle/Application/DB54657E-F34B-4F3E-A650-4C6761A228CC/xxx.iOS.app/xxx.iOS : (null)
	0x101633b74 - /var/containers/Bundle/Application/DB54657E-F34B-4F3E-A650-4C6761A228CC/xxx.iOS.app/xxx.iOS : (null)
	0x101633acc - /var/containers/Bundle/Application/DB54657E-F34B-4F3E-A650-4C6761A228CC/xxx.iOS.app/xxx.iOS : (null)
The app has been terminated.
The app has been terminated.
	0x1005c3bf8 - /var/containers/Bundle/Application/DB54657E-F34B-4F3E-A650-4C6761A228CC/xxx.iOS.app/xxx.iOS : (null)
	0x10096088c - /var/containers/Bundle/Application/DB54657E-F34B-4F3E-A650-4C6761A228CC/xxx.iOS.app/xxx.iOS : (null)
	0x102a7cabc - /var/containers/Bundle/Application/DB54657E-F34B-4F3E-A650-4C6761A228CC/xxx.iOS.app/xxx.iOS : mono_pmip
	0x102b35494 - /var/containers/Bundle/Application/DB54657E-F34B-4F3E-A650-4C6761A228CC/xxx.iOS.app/xxx.iOS : mono_pmip
	0x102b3b9cc - /var/containers/Bundle/Application/DB54657E-F34B-4F3E-A650-4C6761A228CC/xxx.iOS.app/xxx.iOS : mono_pmip
	0x102a59d2c - /var/containers/Bundle/Application/DB54657E-F34B-4F3E-A650-4C6761A228CC/xxx.iOS.app/xxx.iOS : (null)
	0x102c31f94 - /var/containers/Bundle/Application/DB54657E-F34B-4F3E-A650-4C6761A228CC/xxx.iOS.app/xxx.iOS : _Z9__isctypeim
	0x1005c3adc - /var/containers/Bundle/Application/DB54657E-F34B-4F3E-

=================================================================
	Managed Stacktrace:
=================================================================
=================================================================
</details>

**Comment by peterfoot** [comment]
This bug is resolved in 2.0.2019.913

**Comment by PaulVrugt** [comment]
@peterfoot 
I've tried 2.0.2019.913 but the problem persists. The crash log is different though. It now states that it cannot access a disposed object:

<details>
  <summary>Complete error (click to expand)</summary>

**System.ObjectDisposedException:** 'Cannot access a disposed object.
Object name: 'MediaElementRenderer'.'

2019-09-26 11:41:46.307 ***.iOS[712:214701] 
Unhandled Exception:
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'MediaElementRenderer'.
  at Foundation.NSObject.get_SuperHandle () [0x0004a] in /Library/Frameworks/Xamarin.iOS.framework/Versions/13.2.0.42/src/Xamarin.iOS/Foundation/NSObject2.cs:456 
  at UIKit.UIViewController.get_View () [0x0002a] in /Library/Frameworks/Xamarin.iOS.framework/Versions/13.2.0.42/src/Xamarin.iOS/UIViewController.g.cs:3171 
  at InTheHand.Forms.Platform.iOS.MediaElementRenderer.Xamarin.Forms.Platform.iOS.IVisualElementRenderer.get_NativeView () [0x00000] in C:\Users\peter\source\repos\inthehand\InTheHand.Forms\InTheHand.Forms\InTheHand.Forms.Platform.iOS\MediaElementRenderer.cs:40 
  at Xamarin.Forms.Platform.iOS.VisualElementPackager.OnChildRemoved (Xamarin.Forms.VisualElement view) [0x00007] in d:\a\1\s\Xamarin.Forms.Platform.iOS\VisualElementPackager.cs:114 
  at Xamarin.Forms.Platform.iOS.VisualElementPackager.SetElement (Xamarin.Forms.
VisualElement oldElement, Xamarin.Forms.VisualElement newElement) [0x00092] in d:\a\1\s\Xamarin.Forms.Platform.iOS\VisualElementPackager.cs:200 
  at Xamarin.Forms.Platform.iOS.VisualElementPackager.Dispose (System.Boolean disposing) [0x0005c] in d:\a\1\s\Xamarin.Forms.Platform.iOS\VisualElementPackager.cs:73 
  at Xamarin.Forms.Platform.iOS.VisualElementPackager.Dispose () [0x00000] in d:\a\1\s\Xamarin.Forms.Platform.iOS\VisualElementPackager.cs:37 
  at Xamarin.Forms.Platform.iOS.VisualElementRenderer`1[TElement].Dispose (System.Boolean disposing) [0x00058] in <4e367b2cd46d4a02b980ea2aa2a1115b>:0 
  at Foundation.NSObject.Dispose () [0x00000] in /Library/Frameworks/Xamarin.iOS.framework/Versions/13.2.0.42/src/Xamarin.iOS/Foundation/NSObject2.cs:147 
  at Xamarin.Forms.Platform.iOS.DisposeHelpers.DisposeModalAndChildRenderers (Xamarin.Forms.Element view) [0x00042] in d:\a\1\s\Xamarin.Forms.Platform.iOS\DisposeHelpers.cs:23 
  at Xamarin.Forms.Platform.iOS.Platform.Xamarin.Forms.INavigation.PopModalAsync (Sys
encesource/mscorlib/system/runtime/compilerservices/AsyncMethodBuilder.cs:1021 
  at Foundation.NSAsyncSynchronizationContextDispatcher.Apply () [0x00000] in /Library/Frameworks/Xamarin.iOS.framework/Versions/13.2.0.42/src/Xamarin.iOS/Foundation/NSAction.cs:178 
  at (wrapper managed-to-native) UIKit.UIApplication.UIApplicationMain(int,string[],intptr,intptr)
  at UIKit.UIApplication.Main (System.String[] args, System.IntPtr principal, System.IntPtr delegate) [0x00005] in /Library/Frameworks/Xamarin.iOS.framework/Versions/13.2.0.42/src/Xamarin.iOS/UIKit/UIApplication.cs:86 
  at UIKit.UIApplication.Main (System.String[] args, System.String principalClassName, System.String delegateClassName) [0x0000e] in /Library/Frameworks/Xamarin.iOS.framework/Versions/13.2.0.42/src/Xamarin.iOS/UIKit/UIApplication.cs:65 
  at xxx.iOS.Application.Main (System.String[] args) [0x00001] in C:\Users\p.vrugt\Source\Repos\Apps\xxx\xxx.iOS\Main.cs:17 
tem.Boolean animated) [0x00143] in d:\a\1\s\Xamarin.Forms.Platform.iOS\Platform.cs:119 
  at Xamarin.Forms.Application+NavigationImpl.OnPopModal (System.Boolean animated) [0x0005d] in d:\a\1\s\Xamarin.Forms.Core\Application.cs:380 
  at Infoland.Xamarin.Shared.General+<>c__DisplayClass75_0.<GoBackAsync>b__0 () [0x00257] in C:\Users\p.vrugt\Source\Repos\Apps\Infoland.Xamarin.Shared\Infoland.Xamarin.Shared\General\General.cs:1228 
  at Infoland.Xamarin.Shared.General.GoBackAsync () [0x00057] in C:\Users\p.vrugt\Source\Repos\Apps\Infoland.Xamarin.Shared\Infoland.Xamarin.Shared\General\General.cs:1250 
  at Infoland.Xamarin.Shared.Controls.AudioVideo+<>c.<.ctor>b__2_0 () [0x00019] in C:\Users\p.vrugt\Source\Repos\Apps\Infoland.Xamarin.Shared\Infoland.Xamarin.Shared\Controls\DocumentViewer\AudioVideo.cs:27 
  at System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__7_0 (System.Object state) [0x00000] in /Users/builder/jenkins/workspace/xamarin-macios/xamarin-macios/external/mono/mcs/class/refer
2019-09-26 11:41:46.316 xxx.iOS[712:214701] Unhandled managed exception: Cannot access a disposed object.
Object name: 'MediaElementRenderer'. (System.ObjectDisposedException)
  at Foundation.NSObject.get_SuperHandle () [0x0004a] in /Library/Frameworks/Xamarin.iOS.framework/Versions/13.2.0.42/src/Xamarin.iOS/Foundation/NSObject2.cs:456 
  at UIKit.UIViewController.get_View () [0x0002a] in /Library/Frameworks/Xamarin.iOS.framework/Versions/13.2.0.42/src/Xamarin.iOS/UIViewController.g.cs:3171 
  at InTheHand.Forms.Platform.iOS.MediaElementRenderer.Xamarin.Forms.Platform.iOS.IVisualElementRenderer.get_NativeView () [0x00000] in C:\Users\peter\source\repos\inthehand\InTheHand.Forms\InTheHand.Forms\InTheHand.Forms.Platform.iOS\MediaElementRenderer.cs:40 
  at Xamarin.Forms.Platform.iOS.VisualElementPackager.OnChildRemoved (Xamarin.Forms.VisualElement view) [0x00007] in d:\a\1\s\Xamarin.Forms.Platform.iOS\VisualElementPackager.cs:114 
  at Xamarin.Forms.Platform.iOS.VisualElementPackager.SetElement (Xamari
n.Forms.VisualElement oldElement, Xamarin.Forms.VisualElement newElement) [0x00092] in d:\a\1\s\Xamarin.Forms.Platform.iOS\VisualElementPackager.cs:200 
  at Xamarin.Forms.Platform.iOS.VisualElementPackager.Dispose (System.Boolean disposing) [0x0005c] in d:\a\1\s\Xamarin.Forms.Platform.iOS\VisualElementPackager.cs:73 
  at Xamarin.Forms.Platform.iOS.VisualElementPackager.Dispose () [0x00000] in d:\a\1\s\Xamarin.Forms.Platform.iOS\VisualElementPackager.cs:37 
  at Xamarin.Forms.Platform.iOS.VisualElementRenderer`1[TElement].Dispose (System.Boolean disposing) [0x00058] in <4e367b2cd46d4a02b980ea2aa2a1115b>:0 
  at Foundation.NSObject.Dispose () [0x00000] in /Library/Frameworks/Xamarin.iOS.framework/Versions/13.2.0.42/src/Xamarin.iOS/Foundation/NSObject2.cs:147 
  at Xamarin.Forms.Platform.iOS.DisposeHelpers.DisposeModalAndChildRenderers (Xamarin.Forms.Element view) [0x00042] in d:\a\1\s\Xamarin.Forms.Platform.iOS\DisposeHelpers.cs:23 
  at Xamarin.Forms.Platform.iOS.Platform.Xamarin.Forms.INavigation.PopModalAs
ync (System.Boolean animated) [0x00143] in d:\a\1\s\Xamarin.Forms.Platform.iOS\Platform.cs:119 
  at Xamarin.Forms.Application+NavigationImpl.OnPopModal (System.Boolean animated) [0x0005d] in d:\a\1\s\Xamarin.Forms.Core\Application.cs:380 
  at Infoland.Xamarin.Shared.General+<>c__DisplayClass75_0.<GoBackAsync>b__0 () [0x00257] in C:\Users\p.vrugt\Source\Repos\Apps\Infoland.Xamarin.Shared\Infoland.Xamarin.Shared\General\General.cs:1228 
  at Infoland.Xamarin.Shared.General.GoBackAsync () [0x00057] in C:\Users\p.vrugt\Source\Repos\Apps\Infoland.Xamarin.Shared\Infoland.Xamarin.Shared\General\General.cs:1250 
  at Infoland.Xamarin.Shared.Controls.AudioVideo+<>c.<.ctor>b__2_0 () [0x00019] in C:\Users\p.vrugt\Source\Repos\Apps\Infoland.Xamarin.Shared\Infoland.Xamarin.Shared\Controls\DocumentViewer\AudioVideo.cs:27 
  at System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__7_0 (System.Object state) [0x00000] in /Users/builder/jenkins/workspace/xamarin-macios/xamarin-macios/external/mono/mcs/cla
ss/referencesource/mscorlib/system/runtime/compilerservices/AsyncMethodBuilder.cs:1021 
  at Foundation.NSAsyncSynchronizationContextDispatcher.Apply () [0x00000] in /Library/Frameworks/Xamarin.iOS.framework/Versions/13.2.0.42/src/Xamarin.iOS/Foundation/NSAction.cs:178 
  at (wrapper managed-to-native) UIKit.UIApplication.UIApplicationMain(int,string[],intptr,intptr)
  at UIKit.UIApplication.Main (System.String[] args, System.IntPtr principal, System.IntPtr delegate) [0x00005] in /Library/Frameworks/Xamarin.iOS.framework/Versions/13.2.0.42/src/Xamarin.iOS/UIKit/UIApplication.cs:86 
  at UIKit.UIApplication.Main (System.String[] args, System.String principalClassName, System.String delegateClassName) [0x0000e] in /Library/Frameworks/Xamarin.iOS.framework/Versions/13.2.0.42/src/Xamarin.iOS/UIKit/UIApplication.cs:65 
  at xxx.iOS.Application.Main (System.String[] args) [0x00001] in C:\Users\p.vrugt\Source\Repos\Apps\xxx\xxx.iOS\Main.cs:17 
CalabashServer | XTC_SKIP_LPSERVER_TOKEN is no
t in the app environment
CalabashServer | Will start LPServer with identifier: e8754b3cd4c478021b7b5f5654606d3a9bc25485

=================================================================
	Native Crash Reporting
=================================================================
Got a SIGABRT while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries 
used by your application.
=================================================================

=================================================================
	Native stacktrace:
=================================================================
	0x102e623e8 - /var/containers/Bundle/Application/FDBFF7BE-8CB2-4AD5-B58E-6580CEC9D5C7/xxx.iOS.app/xxx.iOS : (null)
	0x102e581d0 - /var/containers/Bundle/Application/FDBFF7BE-8CB2-4AD5-B58E-6580CEC9D5C7/xxx.iOS.app/xxx.iOS : (null)
	0x102e618a8 - /var/containers/Bundle/Application/FDBFF7BE-8CB2-4AD5-B58E-6580CEC9D5C7/xxx.iOS.app/xxx.iOS : (null)
	0x2156fe9fc - /usr/lib/system/libsystem_platform.dylib : <redacted>
	0x215704094 - /usr/lib/system/libsystem_pthread.dylib : <redacted>
	0x2155e3ea8 - /usr/lib/system/libsystem_c.dylib : abort
	0x103022dd8 - /var/containers/Bundle/Application/FDBFF7BE-8CB2-4AD5-B58E-6580CEC9D5C7/xxx.iOS.app/xxx.iOS : xamarin_get_block_descriptor
	0x102ec2fdc - /var/containers/Bundle/Application/FDBFF7BE-8CB2-4AD5-B58E-6580CEC9D5C7/xxx.iOS.app/xxx.iOS : mono_pmip
	0x102e57c04 - /var/containers/Bundle/Application/FDBFF7BE-8CB2-4AD5-B58E-6580CEC9D5C7/xxx.iOS.app/xxx.iOS : (null)
	0x102e566e8 - /var/containers/Bundle/Application/FDBFF7BE-8CB2-4AD5-B58E-6580CEC9D5C7/xxx.iOS.app/xxx.iOS : (null)
	0x102e4c260 - /var/containers/Bundle/Application/FDBFF7BE-8CB2-4AD5-B58E-6580CEC9D5C7/xxx.iOS.app/xxx.iOS : (null)
	0x100f39ddc - /var/containers/Bundle/Application/FDBFF7BE-8CB2-4AD5-B58E-6580CEC9D5C7/xxx.iOS.app/xxx.iOS : (null)
	0x100d0539c - /var/containers/Bundle/Application/FDBFF7BE-8CB2-4AD5-B58E-6580CEC9D5C7/xxx.iOS.app/xxx.iOS : (null)
	0x100d0b3c4 - /var/containers/Bundle/Application/FDBFF7BE-8CB2-4AD5-B58E-6580CEC9D5C7/xxx.iOS.app/xxx.iOS : (null)
	0x101b44b3c - /var/containers/Bundle/Application/FDBFF7BE-8CB2-4AD5-B58E-6580CEC9D5C7/xxx.iOS.app/xxx.iOS : (null)
	0x100efcef4 - /var/containers/Bundle/Application/FDBFF7BE-8CB2-4AD5-B58E-6580CEC9D5C7/xxx.iOS.app/xxx.iOS : (null)
	0x102e69ec4 - /var/containers/Bundle/Application/FDBFF7BE-8CB2-4AD5-B58E-6580CEC9D5C7/xxx.iOS.app/xxx.iOS : mono_pmip
	0x102f26900 - /var/containers/Bundle/Application/FDBFF7BE-8CB2-4AD5-B58E-6580CEC9D5C7/xxx.iOS.app/xxx.iOS : mono_pmip
	0x102f2a19c - /var/containers/Bundle/Application/FDBFF7BE-8CB2-4AD5-B58E-6580CE
C9D5C7/xxx.iOS.app/xxx.iOS : mono_pmip
	0x100b5ed1c - /var/containers/Bundle/Application/FDBFF7BE-8CB2-4AD5-B58E-6580CEC9D5C7/xxx.iOS.app/xxx.iOS : (null)
	0x100b62608 - /var/containers/Bundle/Application/FDBFF7BE-8CB2-4AD5-B58E-6580CEC9D5C7/xxx.iOS.app/xxx.iOS : (null)
	0x216575690 - /System/Library/Frameworks/Foundation.framework/Foundation : <redacted>
	0x215a80728 - /System/Library/Frameworks/CoreFoundation.framework/CoreFoundation : <redacted>
	0x215a806a8 - /System/Library/Frameworks/CoreFoundation.framework/CoreFoundation : <redacted>
	0x215a7ffe0 - /System/Library/Frameworks/CoreFoundation.framework/CoreFoundation : <redacted>
	0x215a7aecc - /System/Library/Frameworks/CoreFoundation.framework/CoreFoundation : <redacted>
	0x215a7a7c0 - /System/Library/Frameworks/CoreFoundation.framework/CoreFoundation : CFRunLoopRunSpecific
	0x217c7b79c - /System/Library/PrivateFrameworks/GraphicsServices.framework/GraphicsServices : GSEventRunModal
	0x2423ffc38 - /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore : UIApplicationMain
	0x101ba3c30 - /var/containers/Bundle/Application/FDBFF7BE-8CB2-4AD5-B58E-6580CEC9D5C7/xxx.iOS.app/xxx.iOS : (null)
	0x101af8e1c - /var/containers/Bundle/Application/FDBFF7BE-8CB2-4AD5-B58E-6580CEC9D5C7/xxx.iOS.app/xxx.iOS : (null)
	0x101af8da4 - /var/containers/Bundle/Application/FDBFF7BE-8CB2-4AD5-B58E-6580CEC9D5C7/xxx.iOS.app/xxx.iOS : (null)
	0x100ba7680 - /var/containers/Bundle/Application/FDBFF7BE-8CB2-4AD5-B58E-6580CEC9D5C7/xxx.iOS.app/xxx.iOS : (null)
	0x100efcef4 - /var/containers/Bundle/Application/FDBFF7BE-8CB2-4AD5-B58E-6580CEC9D5C7/xxx.iOS.app/xxx.iOS : (null)
	0x102e69ec4 - /var/containers/Bundle/Application/FDBFF7BE-8CB2-4AD5-B58E-6580CEC9D5C7/xxx.iOS.app/xxx.iOS : mono_pmip
	0x102f26900 - /var/containers/Bundle/Application/FDBFF7BE-8CB2-4AD5-B58E-6580CEC9D5C7/xxx.iOS.app/xxx.iOS : mono_pmip
	0x102f2cbc8 - /var/containers/Bundle/Application/FDBFF7BE-8CB2-4AD5-B58E-6580CEC9D5C7/xxx.iOS.app/xxx.iOS : mono_pmip
	0x102e481b4 - /var/containers/Bundle/Application/FDBFF7BE-8CB2-4AD5-B58E-6580CEC9D5C7/xxx.iOS.app/xxx.iOS : (null)
	0x1030346e8 - /var/containers/Bundle/Application/FDBFF7BE-8CB2-4AD5-B58E-6580CEC9D5C7/xxx.iOS.app/xxx.iOS : _Z9__isctypeim
	0x100ba7580 - /var/containers/Bundle/Application/FDBFF7BE-8CB2-4AD5-B58E-6580CEC9D5C7/xxx.iOS.app/xxx.iOS : (null)
	0x21553e8e0 - /usr/lib/system/libdyld.dylib : <redacted>

=================================================================
	Basic Fault Address Reporting
=================================================================
Memory around native instruction pointer (0x21568b0dc):0x21568b0cc  fd 7b c1 
a8 c0 03 5f d6 10 29 80 d2 01 10 00 d4  .{...._..)......
0x21568b0dc  c3 00 00 54 fd 7b bf a9 fd 03 00 91 55 d6 ff 97  ...T.{......U...
0x21568b0ec  bf 03 00 91 fd 7b c1 a8 c0 03 5f d6 
90 29 80 d2  ....
.{...._
..)..

0x21568b0fc  01 10 
00 d4 c3 00 
00 54 fd 7b 
bf 
a9 fd 03 00 91  .......T.{......

=================================================================
	Managed Stacktrace:
=================================================================
=================================================================
The app has been terminated.
Failed to Stop app:  An error occurred on client IDB1630274 while executing a reply for topic xvs/idb/16.3.0.274/stop-app
The app has been terminated.
</details>

**Comment by PaulVrugt** [comment]
@peterfoot 
Any news on this? We are still stuck on an old version. I've taken a quick look at the code, but my knowlegde of Xamarin.iOS is not extensive enough to understand what the correct solution for this issue should be.

**Comment by peterfoot** [comment]
I wasn't able to replicate it - even creating a modal dialog and trying different ways to get the renderer to dispose. However I've added some more protection around the disposal which I think should avoid any chance of this happening. The latest should appear on NuGet shortly - 2.0.2019.1004

**Comment by PaulVrugt** [comment]
I've tested it, and I have good and bad news. The good news is that the error about the disposed object is gone. 

The bad news is that a different error is now shown. When popping the dialog, an object reference error now occurs:

System.NullReferenceException: Object reference not set to an instance of an object
  at Xamarin.Forms.Platform.iOS.DisposeHelpers.DisposeModalAndChildRenderers (Xamarin.Forms.Element view) [0x00036] in D:\a\1\s\Xamarin.Forms.Platform.iOS\DisposeHelpers.cs:22 
  at Xamarin.Forms.Platform.iOS.Platform.Xamarin.Forms.INavigation.PopModalAsync (System.Boolean animated) [0x00143] in D:\a\1\s\Xamarin.Forms.Platform.iOS\Platform.cs:119 
  at Xamarin.Forms.Application+NavigationImpl.OnPopModal (System.Boolean animated) [0x0005d] in D:\a\1\s\Xamarin.Forms.Core\Application.cs:380 

~~Maybe it has to do with the fact that we close the popup while the video is still playing?~~
Nope, even when pausing the video before closing the popup the object reference error occurs

Edit:
It seems that the NativeView property of the renderer returns null

**Comment by PaulVrugt** [comment]
any news on this?

**Comment by peterfoot** [comment]
Sorry, I think this was fixed in the 2.0.2019.1021 release.

**Comment by PaulVrugt** [comment]
I'm afraid the 1021 version hasn't fixed the issue. It remains exactly the same. I'll try to create a repro project so we can get to the bottom of this.

**Comment by peterfoot** [comment]
Thanks, that would be very helpful. What version of Xamarin Forms are you using? I will have a look at their code for DisposeHelpers and see what it is trying to do.

**Comment by PaulVrugt** [comment]
I was able to replicate it in a test project, and I now also understand why you coudn't. We have a bit of a special situation in our case. The popmodalasync call to close the dialog with the videoplayer is called from within a "Device.BeginInvokeOnMainThread" method. This is because it is part of a generic method for "going back" in our app, which is not always called from the UI thread. This call ensures that it is.

The error isn't EXACTLY the same, but it is still an error regarding dispose and popping the dialog

However, the old version didn't have any dispose issues with the same code, and no other controls seem to have this issue. So a fix would still be very much appreciated :)

I've attached the repro, don't be fooled by the name of the project, it was originally designed to test something else :)

[CollectionViewSpacing.zip](https://github.com/inthehand/InTheHand.Forms/files/3819768/CollectionViewSpacing.zip)

Edit:
I can confirm when changing the code in our app, the issue is solved. I can now use the MainThread.IsMainThread check for Xamarin.Essentials to see whether or not to use Device.BeginInvokeOnMainThread. This fixes the immediate issue.

**Comment by peterfoot** [comment]
Thanks, I was able to pinpoint the issue. I've reworked the Dispose method to remove the problem. Latest code is in 2.0.2019.1107

**Comment by PaulVrugt** [comment]
Nice! Thanks!

**Comment by PaulVrugt** [comment]
I'm sorry to reopen this, but it turns out we are still experiencing crashes when closing the mediaplayer dialog. Downgrading to version 1.x fixes it. There doesn't seem to be any proper stacktrace. but the error logged by the debugger is shown below.

The error doesn't actually crash the app, but it does lock it up, making it unresponsive and uncloseable.

<details>
<summary>Click to show the error</summary>
=================================================================
	Native Crash Reporting
=================================================================
Got a SIGSEGV while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries 
used by your application.
=================================================================

=================================================================
	Native stacktrace:
=================================================================
	0x1058e5614 - /var/containers/Bundle/Application/85ACFCBF-8B11-4FB0-AE94-C07A9A522088/*****.iOS.app/*****.iOS : (null)
	0x1058db4d4 - /var/containers/Bundle/Application/85ACFCBF-8B11-4FB0-AE94-C07A9A522088/*****.iOS.app/*****.iOS : (null)
	0x1058e9d48 - /var/containers/Bundle/Application/85ACFCBF-8B11-4FB0-AE94-C07A9A522088/*****.iOS.app/*****.iOS : mono_pmip
	0x1888e29fc - /usr/lib/system/libsystem_platform.dylib : <redacted>
	0x189721280 - /System/Library/Frameworks/Foundation.framework/Foundation : <redacted>
	0x18971eb20 - /System/Library/Frameworks/Foundation.framework/Foundation : <redacted>
	0x18ec96d24 - /System/Library/Frameworks/AVFoundation.framework/AVFoundation : <redacted>
	0x188710a38 - /usr/lib/system/libdispatch.dylib : <redacted>
	0x1887117d4 - /usr/lib/system/libdispatch.dylib : <redacted>
	0x1886bf008 - /usr/lib/system/libdispatch.dylib : <redacted>
	0x188c64b20 - /System/Library/Frameworks/CoreFoundation.framework/CoreFoundation : <redacted>
	0x188c5fa58 - /System/Library/Frameworks/CoreFoundation.framework/CoreFoundation : <redacted>
	0x188c5efb4 - /System/Library/Frameworks/CoreFoundation.framework/CoreFoundation : CFRunLoopRunSpecific
	0x18ae6079c - /System/Library/PrivateFrameworks/GraphicsServices.framework/GraphicsServices : GSEventRunModal
	0x1b54c1c38 - /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore : UIApplicationMain
	0x10384e780 - /var/containers/Bundle/Application/85ACFCBF-8B11-4FB0-AE94-C07A9A522088/*****.iOS.app/*****.iOS : (null)
	0x102fbc0bc - /var/containers/Bundle/Application/85ACFCBF-8B11-4FB0-AE94-C07A9A522088/*****.iOS.app/*****.iOS : (null)
	0x102fbbf44 - /var/containers/Bundle/Application/85ACFCBF-8B11-4FB0-AE94-C07A9A522088/*****.iOS.app/*****.iOS : (null)
	0x1008a8360 - /var/containers/Bundle/Application/85ACFCBF-8B11-4FB0-AE94-C07A9A522088/*****.iOS.app/*****.iOS : (null)
	0x10110c034 - /var/containers/Bundle/Application/85ACFCBF-8B11-4FB0-AE94-C07A9A522088/*****.iOS.app/*****.iOS : (null)
	0x1058ed170 - /var/containers/Bundle/Application/85ACFCBF-8B11-4FB0-AE94-C07A9A522088/*****.iOS.app/*****.iOS : mono_pmip
	0x1059ab194 - /var/containers/Bundle/Application/85ACFCBF-8B11-4FB0-AE94-C07A9A522088/*****.iOS.app/*****.iOS : mono_pmip
	0x1059b1450 - /var/containers/Bundle/Application/85ACFCBF-8B11-4FB0-AE94-C07A9A
522088/*****.iOS.app/*****.iOS : mono_pmip
	0x1058cb104 - /var/containers/Bundle/Application/85ACFCBF-8B11-4FB0-AE94-C07A9A522088/*****.iOS.app/*****.iOS : (null)
	0x105aba268 - /var/containers/Bundle/Application/85ACFCBF-8B11-4FB0-AE94-C07A9A522088/*****.iOS.app/*****.iOS : xamarin_localized_string_format_9
	0x1008a8258 - /var/containers/Bundle/Application/85ACFCBF-8B11-4FB0-AE94-C07A9A522088/*****.iOS.app/*****.iOS : (null)
	0x1887228e0 - /usr/lib/system/libdyld.dylib : <redacted>

=================================================================
	Basic Fault Address Reporting
=================================================================
Memory around native instruction pointer (0x187eaa0e0):0x187eaa0d0  1f 04 00 f1 2b 01 00 54 08 00 40 f9 08 81 7d 92  ....+..T..
@...}.
0x187eaa0e0  08 11 40 f9 08 ad 7d 92 08 05 40 f9 08 01 40 39  ..@...}...@...@9
0x187eaa0f0  00 01 00 12 c0 03 5f d6 00 00 80 52 c0 03 5f d6  ......_....R.._.
0x187eaa100  60 02 00 b4 60 02 f8 b6 a8 20 1d f0 08 a1 3c 91  `...`.... .
...<.

=================================================================
	Managed Stacktrace:
=================================================================
	  at <unknown> <0xffffffff>
	  at UIKit.UIApplication:UIApplicationMain <0x00007>
	  at UIKit.UIApplication:Main <0x0002b>
	  at UIKit.UIApplication:Main <0x00043>
	  at *****.iOS.Application:Main <0x0007f>
	  at System.Object:runtime_invoke_dynamic <0x00103>
=================================================================
</details>

**Comment by peterfoot** [comment]
Thanks, looking into this but stacktrace doesn't give much away

**Comment by PaulVrugt** [comment]
yeah I know, but unfortunately there is no more data shown than this.

**Comment by peterfoot** [comment]
Thanks, if it's hanging in the UI thread I have a suspicion that one of the observers is being called when the native AVPlayer is disposed and it can be fixed by changing the order of calls inside the Dispose method. It's tricky because it is probably not reproducable when the debugger is connected.

**Comment by peterfoot** [comment]
Eventually had to rewrite the renderer without implementing as a FastRenderer. This is now working in 2.0.2020. Some details in this post (https://peterfoot.net/2020/01/08/mediaelement-enhancements/)

**Comment by peterfoot** [comment]
All future MediaElement work will take place at https://github.com/xamarin/XamarinCommunityToolkit
